### ISSUE TITLE
Gitlab - Error 404

### ISSUE THREAD

**Issue by npsuav** [nxdefiant/ros_image_to_rtsp#6]
Hi,

Will the new link be opened for public access?
I will like to try the ros topic to rtsp publish.

Thanks.

**Comment by nxdefiant** [comment]
Oops, should be public now. Thank you for bringing this to my attention.

**Comment by npsuav** [comment]
Hi Nxdefiant,

I'm having error with the catkin_make.

I using ubuntu 14.04 on Nvidia TK1 processor, having error in the
catkin_make function.
I install all the package "gstreamer1.0-plugins-good
gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly"
Except "libgstrtspserver-1.0-dev", where "libgstrtspserver-0.10-dev" was
used instead.

The error message are:
`
-- +++ processing catkin package: 'image_to_rtsp'
-- ==> add_subdirectory(ros_image_to_rtsp)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26")
-- checking for module 'gstreamer-1.0'
--   package 'gstreamer-1.0' not found
-- checking for module 'gstreamer-rtsp-server-1.0'
--   package 'gstreamer-rtsp-server-1.0' not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/ROStoRTSP_ws/build
####

Running command: "make -j1 -l1" in "/home/ubuntu/ROStoRTSP_ws/build"

####
Scanning dependencies of target image_to_rtsp_nodelet
[ 50%] Building CXX object
ros_image_to_rtsp/CMakeFiles/image_to_rtsp_nodelet.dir/src/image2rtsp.cpp.o
/home/ubuntu/ROStoRTSP_ws/src/ros_image_to_rtsp/src/image2rtsp.cpp:5:21:
fatal error: gst/gst.h: No such file or directory
 #include
                     ^
compilation terminated.
make[2]: ***
[ros_image_to_rtsp/CMakeFiles/image_to_rtsp_nodelet.dir/src/image2rtsp.cpp.o]
Error 1
make[1]: *** [ros_image_to_rtsp/CMakeFiles/image_to_rtsp_nodelet.dir/all]
Error 2
make: *** [all] Error 2
Invoking "make -j1 -l1" failed
'

Any advice?


Thanks.

**Comment by nxdefiant** [comment]
Sounds like you are trying to mix gstreamer 1.0 with 0.10. That doesn't work.

For the master of image_to_rtsp branch stick to gstreamer 1.0. This means you need libgstrtspserver-1.0-dev. If Ubuntu 14 is still on 0.10 try the gst0.10 branch.
